# Generated by Django 5.2.3 on 2025-07-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.AddField(
            model_name='students',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
